---
title: "my first blog post"
date: 2021-03-04
---


theme: minima
title: Testing
author: Me
email: Math@fake.com
description: > # this means to ignore newlines until "baseurl:"
  Mathematics content here.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
